[package]
name = "installer"
version = "0.1.0"
authors = ["金正伟 <76711619@qq.com>"]
edition = "2018"

[dependencies]
structopt = "0.2.14"
reqwest = "0.9.5"
zip = "0.5"
serde = "1.0"
serde_derive = "1.0"
toml = "0.4.10"
mac_address = "1.0.0"
ipconfig = "0.1.9"
local-ip = "0.1"

[dev-dependencies]
tempfile = "3.0.5"
assert_cmd = "0.10"
predicates = "1.0"
mockito = "0.14.1"
